(() => {
  'use strict'
  const API = window.location.origin
  const $ = (id) => document.getElementById(id)
  const state = { mode: 'edit', xhr: null, report: null, imageBytes: 0 }
  const els = {
    key: $('api-key'), model: $('model'), modelList: $('model-list'), prompt: $('prompt'), image: $('image'), imageMeta: $('image-meta'),
    count: $('count'), size: $('size'), quality: $('quality'), format: $('response-format'), uploadSize: $('upload-size'), advanced: $('advanced'),
    loadModels: $('load-models'), uploadTest: $('upload-test'), runTest: $('run-test'), cancel: $('cancel'),
    progressWrap: document.querySelector('.progress-wrap'), progress: $('progress').firstElementChild, progressLabel: $('progress-label'),
    results: $('results'), summary: $('summary'), metrics: $('metrics'), images: $('images'), error: $('error'), copy: $('copy-report')
  }

  const now = () => performance.now()
  const ms = (value) => `${Math.max(0, value).toFixed(0)} ms`
  const mb = (bytes) => `${(bytes / 1048576).toFixed(2)} MB`
  const esc = (value) => String(value).replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]))
  const key = () => els.key.value.trim()
  const setBusy = (busy) => { [els.loadModels, els.uploadTest, els.runTest].forEach((b) => { b.disabled = busy }); els.cancel.hidden = !busy }
  const progress = (value, label) => { els.progress.style.width = `${Math.min(100, Math.max(0, value))}%`; els.progressLabel.textContent = label || '' }
  const showError = (error) => { els.error.hidden = false; els.error.textContent = error instanceof Error ? error.message : String(error) }
  const clearError = () => { els.error.hidden = true; els.error.textContent = '' }

  function request(method, path, body, contentType) {
    return new Promise((resolve, reject) => {
      const xhr = new XMLHttpRequest(); state.xhr = xhr; const started = now(); let uploadDone = null; let firstByte = null
      xhr.open(method, `${API}${path}`); xhr.setRequestHeader('Authorization', `Bearer ${key()}`); if (contentType) xhr.setRequestHeader('Content-Type', contentType)
      xhr.upload.onprogress = (event) => { if (event.lengthComputable) progress(event.loaded / event.total * 72, `上传中 ${mb(event.loaded)} / ${mb(event.total)}`) }
      xhr.upload.onload = () => { uploadDone = now(); progress(74, '上传完成，等待服务器响应…') }
      xhr.onreadystatechange = () => { if (xhr.readyState === 2 && firstByte === null) { firstByte = now(); progress(82, '服务器已开始响应…') } }
      xhr.onload = () => { state.xhr = null; let data = null; try { data = xhr.responseText ? JSON.parse(xhr.responseText) : null } catch (_) {} resolve({ status: xhr.status, data, text: xhr.responseText, started, uploadDone, firstByte, finished: now(), requestId: xhr.getResponseHeader('X-Oneapi-Request-Id') || data?.request_id || '' }) }
      xhr.onerror = () => { state.xhr = null; reject(new Error('网络连接中断')) }; xhr.onabort = () => { state.xhr = null; reject(new Error('测试已取消')) }; xhr.send(body)
    })
  }

  async function ping() { const values = []; for (let i = 0; i < 5; i++) { const started = now(); const response = await fetch(`${API}/speedtest/ping?i=${i}&t=${Date.now()}`, { cache: 'no-store' }); if (!response.ok) throw new Error(`延迟测试失败（HTTP ${response.status}）`); values.push(now() - started) } values.sort((a,b) => a-b); return { samples: values, median: values[2] } }
  function simulatedBlob(bytes) { return new Blob([new Uint8Array(bytes)], { type: 'application/octet-stream' }) }
  function uploadBody() { const selected = els.uploadSize.value === 'file' && els.image.files[0]; return selected ? els.image.files[0] : simulatedBlob(els.uploadSize.value === 'file' ? 1048576 : Number(els.uploadSize.value)) }
  async function uploadProbe() { const body = uploadBody(); const result = await request('POST', '/speedtest/upload', body, 'application/octet-stream'); if (result.status !== 200) throw new Error(result.data?.error?.message || `上传测速失败（HTTP ${result.status}）`); return { ...result, bytes: body.size, browserUploadMs: (result.uploadDone || result.finished) - result.started, serverReadMs: result.data.server_read_ms, receivedBytes: result.data.received_bytes } }
  function advancedParameters() { const text = els.advanced.value.trim(); if (!text) return {}; let parsed; try { parsed = JSON.parse(text) } catch (_) { throw new Error('高级参数不是有效 JSON') }; if (!parsed || Array.isArray(parsed) || typeof parsed !== 'object') throw new Error('高级参数必须是 JSON 对象'); ['model','prompt','n','size','quality','response_format','stream','image'].forEach((name) => delete parsed[name]); return parsed }
  function imageForm() { const form = new FormData(); form.append('model', els.model.value.trim()); form.append('prompt', els.prompt.value.trim()); form.append('n', String(Math.max(1, Number(els.count.value) || 1))); form.append('size', els.size.value); form.append('quality', els.quality.value); form.append('response_format', els.format.value); Object.entries(advancedParameters()).forEach(([name,value]) => form.append(name, typeof value === 'string' ? value : JSON.stringify(value))); form.append('stream', 'false'); if (state.mode === 'edit' && els.image.files[0]) form.append('image', els.image.files[0], els.image.files[0].name); return form }
  function imageJson() { return JSON.stringify({ ...advancedParameters(), model: els.model.value.trim(), prompt: els.prompt.value.trim(), n: Math.max(1, Number(els.count.value) || 1), size: els.size.value, quality: els.quality.value, response_format: els.format.value, stream: false }) }
  async function loadModels() { clearError(); if (!key()) { showError('请先填写 API Key'); return }; setBusy(true); try { const result = await request('GET', '/v1/models', null); if (result.status !== 200) throw new Error(result.data?.error?.message || `模型加载失败（HTTP ${result.status}）`); const models = (result.data?.data || []).map((item) => item.id).filter(Boolean).sort(); els.modelList.innerHTML = ''; models.forEach((id) => { const option = document.createElement('option'); option.value = id; els.modelList.appendChild(option) }); if (models.length && !els.model.value) els.model.value = models[0] } catch (error) { showError(error) } finally { setBusy(false) } }
  async function runUploadOnly() { clearError(); if (!key()) { showError('请先填写 API Key'); return }; setBusy(true); els.progressWrap.hidden = false; progress(0, '准备上传…'); const started = now(); try { const network = await ping(); const upload = await uploadProbe(); render({ kind: 'upload', network, upload, totalMs: now() - started }) } catch (error) { showError(error) } finally { setBusy(false) } }
  async function runFull() { clearError(); if (!key()) { showError('请先填写 API Key'); return }; if (!els.model.value.trim()) { showError('请填写模型名称'); return }; if (!els.prompt.value.trim()) { showError('请填写提示词'); return }; if (state.mode === 'edit' && !els.image.files[0]) { showError('图生图需要选择参考图片'); return }; if (!window.confirm('真实生图会按当前模型和参数正常消耗额度，确定继续吗？')) return; setBusy(true); els.progressWrap.hidden = false; progress(0, '测试网络延迟…'); const started = now(); try { const network = await ping(); const upload = await uploadProbe(); progress(78, '发送真实生图请求…'); const body = state.mode === 'edit' ? imageForm() : imageJson(); const contentType = state.mode === 'edit' ? null : 'application/json'; const path = state.mode === 'edit' ? '/v1/images/edits' : '/v1/images/generations'; const api = await request('POST', path, body, contentType); if (api.status < 200 || api.status >= 300) throw new Error(api.data?.error?.message || `生图失败（HTTP ${api.status}）`); progress(92, '等待结果图片加载…'); const imageLoadStarted = now(); const images = await loadImages(api.data?.data || []); const imageLoadedAt = now(); render({ kind: 'full', network, upload, api, images, imageLoadMs: imageLoadedAt - imageLoadStarted, totalMs: imageLoadedAt - started }) } catch (error) { showError(error) } finally { setBusy(false) } }
  function loadImages(items) { return Promise.all(items.map((item) => new Promise((resolve) => { const source = item.url || (item.b64_json ? `data:image/png;base64,${item.b64_json}` : ''); if (!source) return resolve({ source: '', loaded: false }); const image = new Image(); image.onload = () => resolve({ source, loaded: true }); image.onerror = () => resolve({ source, loaded: false }); image.src = source }))) }
  function metric(label, value) { return `<div class="metric"><p class="label">${esc(label)}</p><div class="value">${esc(value)}</div></div>` }
  function render(result) { state.report = result; els.results.hidden = false; const pills = [`${result.kind === 'full' ? '完整测试' : '上传测试'}`, `模式：${state.mode === 'edit' ? '图生图' : '文生图'}`, result.network ? `延迟中位数 ${ms(result.network.median)}` : '']; els.summary.innerHTML = pills.filter(Boolean).map((p) => `<span class="pill">${esc(p)}</span>`).join(''); const upload = result.upload; const cards = [metric('浏览器上传完成', ms(upload.browserUploadMs)), metric('服务器读取请求体', ms(upload.serverReadMs)), metric('上传大小', `${mb(upload.bytes)} · ${((upload.bytes / 1048576) / (upload.browserUploadMs / 1000 || 1)).toFixed(2)} MB/s`)]; if (result.kind === 'full') { const api = result.api; cards.push(metric('API 首次响应', api.firstByte ? ms(api.firstByte - api.started) : '—'), metric('API 完整响应', ms(api.finished - api.started)), metric('图片加载完成', ms(result.imageLoadMs)), metric('端到端总耗时', ms(result.totalMs))) } els.metrics.innerHTML = cards.join(''); els.images.innerHTML = ''; if (result.images) result.images.forEach((item) => { if (!item.source) return; const image = document.createElement('img'); image.src = item.source; image.alt = item.loaded ? '生成结果' : '生成结果加载失败'; image.title = item.loaded ? '图片加载完成' : '图片加载失败'; els.images.appendChild(image) }) }
  function reportText() { const r = state.report; if (!r) return ''; const connection = navigator.connection || {}; const referenceBytes = els.image.files[0]?.size || 0; const lines = ['生图网络测速报告', `时间：${new Date().toISOString()}`, `模式：${state.mode === 'edit' ? '图生图' : '文生图'}`, `模型：${els.model.value.trim() || '未填写'}`, `数量：${Math.max(1, Number(els.count.value) || 1)}`, `尺寸：${els.size.value}`, `质量：${els.quality.value}`, `响应格式：${els.format.value}`, `参考图片大小：${referenceBytes ? mb(referenceBytes) : '无'}`, `浏览器网络：${connection.effectiveType || '未知'} / 下行 ${connection.downlink ?? '未知'} Mbps / RTT ${connection.rtt ?? '未知'} ms`, `网络延迟中位数：${r.network ? ms(r.network.median) : '—'}`, `上传大小：${mb(r.upload.bytes)}`, `浏览器上传完成：${ms(r.upload.browserUploadMs)}`, `服务器读取请求体：${ms(r.upload.serverReadMs)}`, `服务器收到字节：${r.upload.receivedBytes}`, `请求 ID：${r.upload.data?.request_id || r.api?.requestId || '—'}`]; if (r.api) lines.push(`HTTP 状态：${r.api.status}`, `API 首次响应：${r.api.firstByte ? ms(r.api.firstByte-r.api.started) : '—'}`, `API 完整响应：${ms(r.api.finished-r.api.started)}`, `图片加载完成：${ms(r.imageLoadMs)}`, `端到端总耗时：${ms(r.totalMs)}`); return lines.join('\n') }
  els.image.addEventListener('change', () => { const file = els.image.files[0]; els.imageMeta.textContent = file ? `${file.name} · ${mb(file.size)}` : '图生图需要选择一张图片。' })
  document.querySelectorAll('.mode').forEach((button) => button.addEventListener('click', () => { state.mode = button.dataset.mode; document.querySelectorAll('.mode').forEach((b) => { const active = b === button; b.classList.toggle('active', active); b.setAttribute('aria-selected', String(active)) }); $('image-field').hidden = state.mode !== 'edit' }))
  els.loadModels.addEventListener('click', loadModels); els.uploadTest.addEventListener('click', runUploadOnly); els.runTest.addEventListener('click', runFull); els.cancel.addEventListener('click', () => state.xhr?.abort()); els.copy.addEventListener('click', async () => { const text = reportText(); if (!text) return; await navigator.clipboard.writeText(text); els.copy.textContent = '已复制'; setTimeout(() => { els.copy.textContent = '复制脱敏报告' }, 1500) })
  $('image-field').hidden = false
})()
