/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
import type { PricingModel } from '../types'

/** Exact model IDs only. Never infer specifications from families or channel names. */
export type VerifiedModelMetadata = Partial<
  Pick<
    PricingModel,
    | 'context_length'
    | 'max_output_tokens'
    | 'knowledge_cutoff'
    | 'release_date'
    | 'parameter_count'
    | 'input_modalities'
    | 'output_modalities'
    | 'capabilities'
  >
> & {
  // Preserve official K/M labels when the source does not publish an exact integer.
  context_display?: string
  max_output_display?: string
  vendor_label: string
  checked_at: string
  sources: string[]
}

export const VERIFIED_MODEL_METADATA: Record<string, VerifiedModelMetadata> = {
  'gpt-6-astra': {
    vendor_label: 'OpenAI',
    checked_at: '2026-09-07',
    sources: [
      'https://developers.openai.com/api/docs/models/gpt-6-astra',
      'https://developers.openai.com/api/docs/changelog',
    ],
    context_length: 1050000,
    max_output_tokens: 128000,
    knowledge_cutoff: '2026-04-30',
    release_date: '2026-09-03',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'vision',
      'reasoning',
      'streaming',
      'function_calling',
      'structured_output',
      'caching',
    ],
  },
  'gpt-5.6-sol': {
    vendor_label: 'OpenAI',
    checked_at: '2026-09-07',
    sources: [
      'https://developers.openai.com/api/docs/models/gpt-5.6-sol',
      'https://developers.openai.com/api/docs/changelog',
    ],
    context_length: 1050000,
    max_output_tokens: 128000,
    knowledge_cutoff: '2026-02-16',
    release_date: '2026-07-09',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'vision',
      'reasoning',
      'streaming',
      'function_calling',
      'structured_output',
      'caching',
    ],
  },
  'gpt-5.6-terra': {
    vendor_label: 'OpenAI',
    checked_at: '2026-09-07',
    sources: [
      'https://developers.openai.com/api/docs/models/gpt-5.6-terra',
      'https://developers.openai.com/api/docs/changelog',
    ],
    context_length: 1050000,
    max_output_tokens: 128000,
    knowledge_cutoff: '2026-02-16',
    release_date: '2026-07-09',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'vision',
      'reasoning',
      'streaming',
      'function_calling',
      'structured_output',
      'caching',
    ],
  },
  'gpt-5.6-luna': {
    vendor_label: 'OpenAI',
    checked_at: '2026-09-07',
    sources: [
      'https://developers.openai.com/api/docs/models/gpt-5.6-luna',
      'https://developers.openai.com/api/docs/changelog',
    ],
    context_length: 1050000,
    max_output_tokens: 128000,
    knowledge_cutoff: '2026-02-16',
    release_date: '2026-07-09',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'vision',
      'reasoning',
      'streaming',
      'function_calling',
      'structured_output',
      'caching',
    ],
  },
  'gpt-5.5': {
    vendor_label: 'OpenAI',
    checked_at: '2026-09-07',
    sources: [
      'https://developers.openai.com/api/docs/models/gpt-5.5',
      'https://developers.openai.com/api/docs/changelog',
    ],
    context_length: 1050000,
    max_output_tokens: 128000,
    knowledge_cutoff: '2025-12-01',
    release_date: '2026-04-24',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'vision',
      'reasoning',
      'streaming',
      'function_calling',
      'structured_output',
      'caching',
    ],
  },
  'gpt-5.4': {
    vendor_label: 'OpenAI',
    checked_at: '2026-09-07',
    sources: [
      'https://developers.openai.com/api/docs/models/gpt-5.4',
      'https://developers.openai.com/api/docs/changelog',
    ],
    context_length: 1050000,
    max_output_tokens: 128000,
    knowledge_cutoff: '2025-08-31',
    release_date: '2026-03-05',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'vision',
      'reasoning',
      'streaming',
      'function_calling',
      'structured_output',
      'caching',
    ],
  },
  'gpt-5.4-mini': {
    vendor_label: 'OpenAI',
    checked_at: '2026-09-07',
    sources: [
      'https://developers.openai.com/api/docs/models/gpt-5.4-mini',
      'https://developers.openai.com/api/docs/changelog',
    ],
    context_length: 400000,
    max_output_tokens: 128000,
    knowledge_cutoff: '2025-08-31',
    release_date: '2026-03-17',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'vision',
      'reasoning',
      'streaming',
      'function_calling',
      'structured_output',
      'caching',
    ],
  },
  'gpt-image-2': {
    vendor_label: 'OpenAI',
    checked_at: '2026-09-07',
    sources: ['https://developers.openai.com/api/docs/models/gpt-image-2'],
    input_modalities: ['text', 'image'],
    output_modalities: ['image'],
  },
  'claude-fable-5-1': {
    vendor_label: 'Anthropic',
    checked_at: '2026-09-07',
    sources: ['https://platform.claude.com/docs/en/models/fable-5-1/overview'],
    context_display: '1M',
    max_output_display: '128K',
    knowledge_cutoff: '2026-06',
    release_date: '2026-09-01',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: ['vision', 'reasoning', 'streaming', 'tools', 'caching'],
  },
  'claude-fable-5': {
    vendor_label: 'Anthropic',
    checked_at: '2026-09-07',
    sources: ['https://platform.claude.com/docs/en/models/fable-5/overview'],
    context_display: '1M',
    max_output_display: '128K',
    knowledge_cutoff: '2026-01',
    release_date: '2026-06-09',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: ['vision', 'reasoning', 'streaming', 'tools', 'caching'],
  },
  'claude-haiku-4-5-20251001': {
    vendor_label: 'Anthropic',
    checked_at: '2026-09-07',
    sources: ['https://platform.claude.com/docs/en/models/haiku-4-5/overview'],
    context_display: '200K',
    max_output_display: '64K',
    knowledge_cutoff: '2025-02',
    release_date: '2025-10-15',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: ['vision', 'reasoning', 'streaming', 'tools', 'caching'],
  },
  'claude-opus-4-5-20251101': {
    vendor_label: 'Anthropic',
    checked_at: '2026-09-07',
    sources: ['https://platform.claude.com/docs/en/models/opus-4-5/overview'],
    context_display: '200K',
    max_output_display: '64K',
    knowledge_cutoff: '2025-05',
    release_date: '2025-11-24',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: ['vision', 'reasoning', 'streaming', 'tools', 'caching'],
  },
  'claude-opus-4-6': {
    vendor_label: 'Anthropic',
    checked_at: '2026-09-07',
    sources: ['https://platform.claude.com/docs/en/models/opus-4-6/overview'],
    context_display: '1M',
    max_output_display: '128K',
    knowledge_cutoff: '2025-05',
    release_date: '2026-02-05',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: ['vision', 'reasoning', 'streaming', 'tools', 'caching'],
  },
  'claude-opus-4-7': {
    vendor_label: 'Anthropic',
    checked_at: '2026-09-07',
    sources: ['https://platform.claude.com/docs/en/models/opus-4-7/overview'],
    context_display: '1M',
    max_output_display: '128K',
    knowledge_cutoff: '2026-01',
    release_date: '2026-04-16',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: ['vision', 'reasoning', 'streaming', 'tools', 'caching'],
  },
  'claude-opus-4-8': {
    vendor_label: 'Anthropic',
    checked_at: '2026-09-07',
    sources: ['https://platform.claude.com/docs/en/models/opus-4-8/overview'],
    context_display: '1M',
    max_output_display: '128K',
    knowledge_cutoff: '2026-01',
    release_date: '2026-05-28',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: ['vision', 'reasoning', 'streaming', 'tools', 'caching'],
  },
  'claude-opus-5': {
    vendor_label: 'Anthropic',
    checked_at: '2026-09-07',
    sources: ['https://platform.claude.com/docs/en/models/opus-5/overview'],
    context_display: '1M',
    max_output_display: '128K',
    knowledge_cutoff: '2026-05',
    release_date: '2026-07-24',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: ['vision', 'reasoning', 'streaming', 'tools', 'caching'],
  },
  'claude-sonnet-4-5-20250929': {
    vendor_label: 'Anthropic',
    checked_at: '2026-09-07',
    sources: ['https://platform.claude.com/docs/en/models/sonnet-4-5/overview'],
    context_display: '200K',
    max_output_display: '64K',
    knowledge_cutoff: '2025-01',
    release_date: '2025-09-29',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: ['vision', 'reasoning', 'streaming', 'tools', 'caching'],
  },
  'claude-sonnet-4-6': {
    vendor_label: 'Anthropic',
    checked_at: '2026-09-07',
    sources: ['https://platform.claude.com/docs/en/models/sonnet-4-6/overview'],
    context_display: '1M',
    max_output_display: '128K',
    knowledge_cutoff: '2025-08',
    release_date: '2026-02-17',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: ['vision', 'reasoning', 'streaming', 'tools', 'caching'],
  },
  'claude-sonnet-5': {
    vendor_label: 'Anthropic',
    checked_at: '2026-09-07',
    sources: ['https://platform.claude.com/docs/en/models/sonnet-5/overview'],
    context_display: '1M',
    max_output_display: '128K',
    knowledge_cutoff: '2026-01',
    release_date: '2026-06-30',
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: ['vision', 'reasoning', 'streaming', 'tools', 'caching'],
  },
  'gemini-3.1-pro-preview': {
    vendor_label: 'Google',
    checked_at: '2026-09-07',
    sources: [
      'https://ai.google.dev/gemini-api/docs/models/gemini-3.1-pro-preview',
      'https://ai.google.dev/gemini-api/docs/changelog',
    ],
    context_length: 1048576,
    max_output_tokens: 65536,
    release_date: '2026-02-19',
    input_modalities: ['text', 'image', 'audio', 'video', 'file'],
    output_modalities: ['text'],
    capabilities: [
      'vision',
      'reasoning',
      'function_calling',
      'structured_output',
      'caching',
    ],
  },
  'gemini-3.5-flash': {
    vendor_label: 'Google',
    checked_at: '2026-09-07',
    sources: [
      'https://ai.google.dev/gemini-api/docs/models/gemini-3.5-flash',
      'https://ai.google.dev/gemini-api/docs/changelog',
    ],
    context_length: 1048576,
    max_output_tokens: 65536,
    release_date: '2026-05-19',
    input_modalities: ['text', 'image', 'audio', 'video', 'file'],
    output_modalities: ['text'],
    capabilities: [
      'vision',
      'reasoning',
      'function_calling',
      'structured_output',
      'caching',
    ],
  },
  'gemini-3.6-flash': {
    vendor_label: 'Google',
    checked_at: '2026-09-07',
    sources: [
      'https://ai.google.dev/gemini-api/docs/models/gemini-3.6-flash',
      'https://ai.google.dev/gemini-api/docs/changelog',
    ],
    context_length: 1048576,
    max_output_tokens: 65536,
    release_date: '2026-07-21',
    input_modalities: ['text', 'image', 'audio', 'video', 'file'],
    output_modalities: ['text'],
    capabilities: [
      'vision',
      'reasoning',
      'function_calling',
      'structured_output',
      'caching',
    ],
  },
  'gemini-3.7-flash': {
    vendor_label: 'Google',
    checked_at: '2026-09-07',
    sources: [
      'https://ai.google.dev/gemini-api/docs/models/gemini-3.7-flash',
      'https://ai.google.dev/gemini-api/docs/changelog',
    ],
    context_length: 1048576,
    max_output_tokens: 65536,
    release_date: '2026-08-13',
    input_modalities: ['text', 'image', 'audio', 'video', 'file'],
    output_modalities: ['text'],
    capabilities: [
      'vision',
      'reasoning',
      'function_calling',
      'structured_output',
      'caching',
    ],
  },
  'gemini-3.8-flash': {
    vendor_label: 'Google',
    checked_at: '2026-09-07',
    sources: [
      'https://ai.google.dev/gemini-api/docs/models/gemini-3.8-flash',
      'https://ai.google.dev/gemini-api/docs/changelog',
    ],
    context_length: 1048576,
    max_output_tokens: 65536,
    release_date: '2026-09-02',
    input_modalities: ['text', 'image', 'audio', 'video', 'file'],
    output_modalities: ['text'],
    capabilities: [
      'vision',
      'reasoning',
      'function_calling',
      'structured_output',
      'caching',
    ],
  },
  'nano-banana-2': {
    vendor_label: 'Google',
    checked_at: '2026-09-07',
    sources: [
      'https://ai.google.dev/gemini-api/docs/models/gemini-3.1-flash-image',
      'https://ai.google.dev/gemini-api/docs/models',
    ],
    context_length: 131072,
    max_output_tokens: 32768,
    input_modalities: ['text', 'image', 'video', 'file'],
    output_modalities: ['text', 'image'],
    capabilities: ['vision'],
  },
  'nano-banana-pro': {
    vendor_label: 'Google',
    checked_at: '2026-09-07',
    sources: [
      'https://ai.google.dev/gemini-api/docs/models/gemini-3-pro-image',
      'https://ai.google.dev/gemini-api/docs/models',
    ],
    context_length: 65536,
    max_output_tokens: 32768,
    input_modalities: ['text', 'image'],
    output_modalities: ['text', 'image'],
    capabilities: ['vision'],
  },
  'glm-4.5': {
    vendor_label: 'Zhipu AI',
    checked_at: '2026-09-07',
    sources: ['https://docs.bigmodel.cn/cn/guide/models/text/glm-4.5.md'],
    context_display: '128K',
    max_output_display: '96K',
    input_modalities: ['text'],
    output_modalities: ['text'],
    capabilities: ['reasoning', 'function_calling', 'streaming', 'caching'],
  },
  'glm-4.6': {
    vendor_label: 'Zhipu AI',
    checked_at: '2026-09-07',
    sources: ['https://docs.bigmodel.cn/cn/guide/models/text/glm-4.6.md'],
    context_display: '200K',
    max_output_display: '128K',
    input_modalities: ['text'],
    output_modalities: ['text'],
    capabilities: ['reasoning', 'function_calling', 'streaming', 'caching'],
  },
  'glm-4.7': {
    vendor_label: 'Zhipu AI',
    checked_at: '2026-09-07',
    sources: ['https://docs.bigmodel.cn/cn/guide/models/text/glm-4.7.md'],
    context_display: '200K',
    max_output_display: '128K',
    input_modalities: ['text'],
    output_modalities: ['text'],
    capabilities: ['reasoning', 'function_calling', 'streaming', 'caching'],
  },
  'glm-5': {
    vendor_label: 'Zhipu AI',
    checked_at: '2026-09-07',
    sources: ['https://docs.bigmodel.cn/cn/guide/models/text/glm-5.md'],
    context_display: '200K',
    max_output_display: '128K',
    input_modalities: ['text'],
    output_modalities: ['text'],
    capabilities: ['reasoning', 'function_calling', 'streaming', 'caching'],
  },
  'glm-5-turbo': {
    vendor_label: 'Zhipu AI',
    checked_at: '2026-09-07',
    sources: ['https://docs.bigmodel.cn/cn/guide/models/text/glm-5-turbo.md'],
    context_display: '200K',
    max_output_display: '128K',
    input_modalities: ['text'],
    output_modalities: ['text'],
    capabilities: ['reasoning', 'function_calling', 'streaming', 'caching'],
  },
  'glm-5.1': {
    vendor_label: 'Zhipu AI',
    checked_at: '2026-09-07',
    sources: ['https://docs.bigmodel.cn/cn/guide/models/text/glm-5.1.md'],
    context_display: '200K',
    max_output_display: '128K',
    input_modalities: ['text'],
    output_modalities: ['text'],
    capabilities: ['reasoning', 'function_calling', 'streaming', 'caching'],
  },
  'glm-5.2': {
    vendor_label: 'Zhipu AI',
    checked_at: '2026-09-07',
    sources: ['https://docs.bigmodel.cn/cn/guide/models/text/glm-5.2.md'],
    context_display: '1M',
    max_output_display: '128K',
    input_modalities: ['text'],
    output_modalities: ['text'],
    capabilities: ['reasoning', 'function_calling', 'streaming', 'caching'],
  },
  'glm-5.3-flash': {
    vendor_label: 'Zhipu AI',
    checked_at: '2026-09-07',
    sources: ['https://docs.bigmodel.cn/cn/guide/models/vlm/glm-5.3-flash.md'],
    context_display: '1M',
    max_output_display: '128K',
    input_modalities: ['text', 'image', 'video', 'file'],
    output_modalities: ['text'],
    capabilities: [
      'vision',
      'reasoning',
      'function_calling',
      'streaming',
      'caching',
    ],
  },
  'glm-4.5-air': {
    vendor_label: 'Zhipu AI',
    checked_at: '2026-09-07',
    sources: [
      'https://docs.bigmodel.cn/cn/guide/models/text/glm-4.5.md',
      'https://docs.bigmodel.cn/api-reference/%E6%A8%A1%E5%9E%8B-api/%E5%AF%B9%E8%AF%9D%E8%A1%A5%E5%85%A8.md',
    ],
    context_display: '128K',
    max_output_display: '96K',
    input_modalities: ['text'],
    output_modalities: ['text'],
    capabilities: ['reasoning', 'function_calling', 'streaming', 'caching'],
  },
  'glm-5.3': {
    vendor_label: 'Zhipu AI',
    checked_at: '2026-09-07',
    sources: ['https://docs.bigmodel.cn/cn/guide/models/text/glm-5.3.md'],
    context_display: '1M',
    max_output_display: '128K',
    input_modalities: ['text'],
    output_modalities: ['text'],
    capabilities: ['reasoning', 'function_calling', 'streaming', 'caching'],
  },
  'qwen3.8-max': {
    vendor_label: 'Alibaba (Qwen)',
    checked_at: '2026-09-07',
    sources: ['https://help.aliyun.com/zh/model-studio/qwen3-8-max'],
    context_length: 1000000,
    max_output_tokens: 131072,
    input_modalities: ['text', 'image', 'video'],
    output_modalities: ['text'],
    capabilities: [
      'vision',
      'function_calling',
      'structured_output',
      'caching',
    ],
  },
  'qwen3.7-max': {
    vendor_label: 'Alibaba (Qwen)',
    checked_at: '2026-09-07',
    sources: ['https://help.aliyun.com/zh/model-studio/qwen3-7-max'],
    context_length: 1000000,
    max_output_tokens: 131072,
    input_modalities: ['text'],
    output_modalities: ['text'],
    capabilities: ['function_calling', 'structured_output', 'caching'],
  },
  'qwen3.8-27b': {
    vendor_label: 'Alibaba (Qwen)',
    checked_at: '2026-09-07',
    sources: ['https://help.aliyun.com/zh/model-studio/qwen3-8-27b'],
    context_length: 1000000,
    max_output_tokens: 131072,
    input_modalities: ['text', 'image', 'video'],
    output_modalities: ['text'],
    capabilities: [
      'vision',
      'function_calling',
      'structured_output',
      'caching',
    ],
  },
  'deepseek-v4-flash-0731': {
    vendor_label: 'DeepSeek',
    checked_at: '2026-09-07',
    sources: [
      'https://api-docs.deepseek.com/zh-cn/quick_start/pricing/',
      'https://api-docs.deepseek.com/zh-cn/updates/',
    ],
    context_display: '1M',
    max_output_display: '384K',
    release_date: '2026-07-31',
    input_modalities: ['text'],
    output_modalities: ['text'],
    capabilities: [
      'reasoning',
      'function_calling',
      'streaming',
      'json_mode',
      'caching',
    ],
  },
  'deepseek-v4-pro-0813': {
    vendor_label: 'DeepSeek',
    checked_at: '2026-09-07',
    sources: [
      'https://api-docs.deepseek.com/zh-cn/quick_start/pricing/',
      'https://api-docs.deepseek.com/zh-cn/updates/',
    ],
    context_display: '1M',
    max_output_display: '384K',
    release_date: '2026-08-13',
    input_modalities: ['text'],
    output_modalities: ['text'],
    capabilities: [
      'reasoning',
      'function_calling',
      'streaming',
      'json_mode',
      'caching',
    ],
  },
  'kimi-k3': {
    vendor_label: 'Moonshot AI',
    checked_at: '2026-09-07',
    sources: [
      'https://platform.kimi.com/docs/guide/kimi-k3-quickstart.md',
      'https://platform.kimi.com/docs/api/chat.md',
      'https://platform.kimi.com/docs/pricing/chat-k3.md',
    ],
    context_length: 1048576,
    max_output_tokens: 1048576,
    parameter_count: '2.8T',
    input_modalities: ['text', 'image', 'video'],
    output_modalities: ['text'],
    capabilities: [
      'vision',
      'reasoning',
      'function_calling',
      'structured_output',
      'caching',
    ],
  },
  'minimax-m3': {
    vendor_label: 'MiniMax',
    checked_at: '2026-09-07',
    sources: [
      'https://platform.minimaxi.com/docs/guides/models-intro.md',
      'https://platform.minimaxi.com/docs/api-reference/text-anthropic-api.md',
    ],
    context_display: '1M',
    input_modalities: ['text', 'image', 'video'],
    output_modalities: ['text'],
    capabilities: ['vision', 'reasoning', 'tools', 'streaming'],
  },
  'grok-4.5': {
    vendor_label: 'xAI',
    checked_at: '2026-09-07',
    sources: ['https://docs.x.ai/developers/models/grok-4.5'],
    context_length: 500000,
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'vision',
      'reasoning',
      'function_calling',
      'structured_output',
    ],
  },
  'grok-4.6': {
    vendor_label: 'xAI',
    checked_at: '2026-09-07',
    sources: ['https://docs.x.ai/developers/models/grok-4.6'],
    context_length: 500000,
    input_modalities: ['text', 'image'],
    output_modalities: ['text'],
    capabilities: [
      'vision',
      'reasoning',
      'function_calling',
      'structured_output',
    ],
  },
  'grok-imagine-video-1.5-preview': {
    vendor_label: 'xAI',
    checked_at: '2026-09-07',
    sources: [
      'https://docs.x.ai/developers/models/grok-imagine-video-1.5-preview',
    ],
    input_modalities: ['text', 'image', 'audio'],
    output_modalities: ['video'],
  },
}
